[build]
  # 1) installa Poetry, 
  # 2) disabilita la venv,
  # 3) installa deps,
  # 4) build
  
  command = """
    curl -sSL https://install.python-poetry.org | python3 - \
    && export PATH="$HOME/.local/bin:$PATH" \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi \
    && poetry run build
  """
  
  # Specifica dove si trova l'output statico 
  # del mio freezer
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.12"
