description: >
  Ecco alcuni esempi di cosa potrai ottenere pagandomi 
  2,5 / 5 / 10 ore. Ricorda che posso fare molto altro 
  per te e per la tua azienda, per cui non esitare a 
  contattarmi se desideri richiedermi un preventivo per 
  un lavoro specifico.

examples:
  - title: Ottimizzazione dei tuoi profili su Google e TripAdvisor
    description: >
      Modifico le informazioni sui tuoi profili, aggiornando le 
      informazioni sulla tua attività commerciale. Quando posso e 
      se me le fornisci, inserisco le tue nuove fotografie 
      promozionali per presentare al meglio la tua attività.
    duration: 2.5

  - title: Promozione dell'attività su due social network per un mese
    description: >
      Creerò un post la settimana per la vostra attività commerciale 
      che posterò su due social network (solitamente Google My Business + 
      Instagram, ma potete sceglierlo voi).
      
      <br><br>**Extra che possono essere aggiunti:**<br>         
      <ul><li>Due post la settimana anziché uno hanno un costo addizionale di 2,5 Ore di lavoro.</li>   
      <li>Tre post la settimana anziché uno hanno un costo addizionale di 5 Ore di lavoro.</li></ul>
      
      <br>**Da sapere prima di richiedere il lavoro**<br>        
      Dovrete provvedere voi a fornirmi fotografie di alta 
      qualità del locale e dei vostri prodotti / servizi, 
      che poi provvederò a riadattare nel formato richiesto 
      dai social network. Nel caso in cui non abbiate a 
      disposizione materiale fotografico, posso portare da 
      voi un fotografo professionista ad un costo aggiuntivo.
    duration: 2.5

  - title: Registrazione di un dominio web e di un email aziendale
    description: >
      Registro per tuo conto un tuo dominio web aziendale 
      del tipo *www.azienda.com* e gli associo uno o 
      più indirizzi email aziendali, del tipo 
      *mario.rossi@azienda.com*
    duration: 2.5

  - title: Listino prezzi in due lingue con carta dei vini e bevande
    description: >
      Creo per te un listino prezzi cartaceo in due lingue 
      (generalmente Italiano + Inglese), comprensivo di una 
      carta dei vini di massimo due pagine e di una carta delle 
      bevande e caffetteria di massimo una pagina. La stampa su 
      carta dei menù non è compresa nel prezzo.
    duration: 5

  - title: Dominio + Email + Landing page basilare
    description: >
      Registro per te un dominio web, registro per te una 
      o più email aziendali e creo una semplice landing page 
      in una sola lingua (solitamente Italiano) che presenti 
      i link ai tuoi profili social ed alle tue gallerie 
      fotografiche esterne. Incluso nel prezzo un aggiornamento 
      alla landing page da effettuare entro 12 mesi.
    duration: 5

  - title: Listino prezzi in quattro lingue con carta dei vini e bevande
    description: >
      Creo per te un listino prezzi cartaceo in quattro lingue 
      (generalmente Italiano + Inglese + Francese + Tedesco), comprensivo di una 
      carta dei vini di massimo 60 voci e di una carta delle 
      bevande e cafeteria di massimo una pagina. Viene inoltre consegnata 
      per essere in regola con la legge, una tabella degli allergeni che andrà  
      compilata a mano a cura del cuoco del ristorante.  
      
      <br>**Extra che possono essere aggiunti:**<br>         
      <ul><li>Ogni lingua extra nel menù ha un costo addizionale di 1 Ora di lavoro.</li>   
      <li>Dopo le prime 60 comprese, ogni 30 voci extra da inserire nella carta dei vini viene aggiunto un costo addizionale di 1 Ora di lavoro.</li>   
      <li>La creazione dei listini da esterno hanno un costo addizionale di 2 Ore di lavoro.</li></ul>
      
      <br>**Da sapere prima di richiedere il lavoro**<br>        
      La stampa su carta dei menù non è compresa nel prezzo.
    duration: 7

  - title: Dominio + Email + Landing page in due lingue
    description: >
      Registro per te un dominio web, registro per te una 
      o più email aziendali e creo una landing page di media 
      lunghezza in due lingue (solitamente Italiano + Inglese) 
      che presenti la tua azienda, mostri una breve galleria 
      fotografica sui tuoi prodotti e servizi (massimo 16 
      fotografie di prodotti e servizi) e una galleria fotografica che presenti 
      il tuo lavoro (massimo 16 fotografie). Incluso nel prezzo  
      un aggiornamento alla landing page da effettuare entro 
      12 mesi.
      
      <br><br>**Da sapere prima di richiedere il lavoro**<br>        
      Dovrete provvedere voi a fornirmi fotografie di alta 
      qualità del locale e dei vostri prodotti / servizi, 
      che poi provvederò a riadattare nel formato richiesto 
      per la pubblicazione sul vostro sito. Nel caso in cui 
      non abbiate a disposizione materiale fotografico, posso 
      portare da voi un fotografo professionista ad un costo 
      aggiuntivo.
    duration: 10
