address: Viale 4 Novembre N. 89, 30132 Venezia
email: privacy_3725@cesco.it
responsabile: Francesco Maida
service-provider:
  name: GitHub
  url: https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement